spring:
  application:
    name: gateway-service
  config:
    import:
      - optional:nacos:gateway-service.yaml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.101:8848
      config:
        server-addr: 192.168.10.101:8848
        file-extension: yaml  # 配置文件格式
    gateway:
      discovery:
        locator:
          enabled: true  # 开启服务名路由（如/user-service/**转发到user-service）
      routes:
        # 用户服务路由
        - id: core-service
          uri: lb://core-service  # 负载均衡指向Nacos中的服务
          predicates:
            - Path=/api/**
server:
  port: 80  # 网关端口