mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.lsx.system: debug

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.10.101}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:smart_community}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    hikari:
      maximum-pool-size: 50 # 必须加上这个，解决连接池干涸
  redis:
    host: ${REDIS_HOST:192.168.10.101} # 必须加上这个，解决 localhost 报错
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:1234} # 如果没密码就删掉或留空
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.10.101}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1

  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8080}
        port: ${SENTINEL_TRANSPORT_PORT:8719}
      datasource:
        param-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: sentinel-system-param-flow-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: param-flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: sentinel-system-degrade-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade



