mybatis-plus:
  mapper-locations: classpath*:com/lsx/user/mapper/*.xml
  type-aliases-package: com.lsx.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.lsx.user.mapper: debug

knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: 用户服务 API
    description: 用户管理、登录注册
    version: 1.0
    contact:
      name: lsx
      email: 2428513271@qq.com

jwt:
  secret: "mySecretKeyForJWTGenerationInSmartCommunitySystem2024"
  expiration: 86400000
